/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Layout;

import DAO.cad_funcionariosDAO;
import beans.Cad_funcionarios;
import java.util.List;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author emill
 */
public class TelaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form TelaPrincipal
     */
    public TelaPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonPesquisar = new javax.swing.JButton();
        jButtonCadastrar = new javax.swing.JButton();
        jButtonAtualizar = new javax.swing.JButton();
        jButtonExcluir = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jComboAcessosis = new javax.swing.JComboBox<>();
        jComboCargo = new javax.swing.JComboBox<>();
        jTextID = new javax.swing.JTextField();
        jTextMatricula = new javax.swing.JTextField();
        jTextCPF = new javax.swing.JTextField();
        jTextNome = new javax.swing.JTextField();
        jTextSalario = new javax.swing.JTextField();
        jTextSenhaFunc = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelaFuncionarios = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Controle Funcionarios");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(null);

        jButtonPesquisar.setText("Pesquisar");
        jButtonPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPesquisarActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonPesquisar);
        jButtonPesquisar.setBounds(480, 80, 90, 30);

        jButtonCadastrar.setText("Cadastrar");
        jButtonCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCadastrarActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonCadastrar);
        jButtonCadastrar.setBounds(10, 230, 90, 23);

        jButtonAtualizar.setText("Atualizar");
        jButtonAtualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAtualizarActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonAtualizar);
        jButtonAtualizar.setBounds(130, 230, 90, 23);

        jButtonExcluir.setText("Excluir");
        jButtonExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonExcluirActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonExcluir);
        jButtonExcluir.setBounds(250, 230, 90, 23);

        jLabel1.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 14)); // NOI18N
        jLabel1.setText("Salário");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(290, 130, 50, 30);

        jLabel2.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 14)); // NOI18N
        jLabel2.setText("ID");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(10, 40, 40, 30);

        jLabel3.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 14)); // NOI18N
        jLabel3.setText("Matricula");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(160, 40, 70, 30);

        jLabel4.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 14)); // NOI18N
        jLabel4.setText("Nome");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(10, 80, 50, 30);

        jLabel5.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 14)); // NOI18N
        jLabel5.setText("CPF");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(370, 40, 50, 30);

        jLabel6.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 14)); // NOI18N
        jLabel6.setText("Senha");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(410, 180, 50, 30);

        jLabel7.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 14)); // NOI18N
        jLabel7.setText("Cargo");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(10, 130, 50, 30);

        jLabel8.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 10)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Não: 0 - Sim: 1");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(230, 180, 80, 20);

        jLabel9.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 14)); // NOI18N
        jLabel9.setText("Acesso ao sistema");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(10, 180, 120, 30);

        jComboAcessosis.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0", "1" }));
        jComboAcessosis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboAcessosisActionPerformed(evt);
            }
        });
        getContentPane().add(jComboAcessosis);
        jComboAcessosis.setBounds(140, 180, 80, 30);

        jComboCargo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Assistente administrativo(a)", "Assistente técnico", "Analista financeiro", "Analista de projeto", "Analista de software", "Analista de TI", "Consultor(a) tecnólogo", "Estagiário(a)", "Líder de projeto", "Estagiaria", "Orelha" }));
        getContentPane().add(jComboCargo);
        jComboCargo.setBounds(60, 130, 210, 30);

        jTextID.setEnabled(false);
        jTextID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextIDActionPerformed(evt);
            }
        });
        getContentPane().add(jTextID);
        jTextID.setBounds(30, 40, 120, 30);
        getContentPane().add(jTextMatricula);
        jTextMatricula.setBounds(230, 40, 120, 30);
        getContentPane().add(jTextCPF);
        jTextCPF.setBounds(410, 40, 160, 30);
        getContentPane().add(jTextNome);
        jTextNome.setBounds(60, 80, 410, 30);
        getContentPane().add(jTextSalario);
        jTextSalario.setBounds(340, 130, 140, 30);
        getContentPane().add(jTextSenhaFunc);
        jTextSenhaFunc.setBounds(470, 180, 140, 30);

        jLabel12.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 18)); // NOI18N
        jLabel12.setText("Dados do Funcionário");
        getContentPane().add(jLabel12);
        jLabel12.setBounds(10, 10, 190, 20);

        tabelaFuncionarios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Matricula", "Nome", "CPF"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabelaFuncionarios.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelaFuncionariosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabelaFuncionarios);
        if (tabelaFuncionarios.getColumnModel().getColumnCount() > 0) {
            tabelaFuncionarios.getColumnModel().getColumn(0).setMinWidth(50);
            tabelaFuncionarios.getColumnModel().getColumn(0).setPreferredWidth(50);
            tabelaFuncionarios.getColumnModel().getColumn(0).setMaxWidth(50);
        }

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(10, 270, 670, 140);

        setSize(new java.awt.Dimension(703, 460));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCadastrarActionPerformed
        // TODO add your handling code here:
        String cpf = jTextCPF.getText();
        int matricula = Integer.parseInt(jTextMatricula.getText());
        String nome = jTextNome.getText();
        double salario = Integer.parseInt(jTextSalario.getText());
        String senha = jTextSenhaFunc.getText();
        int acessosis = Integer.parseInt(jComboAcessosis.getSelectedItem().toString());
        String cargo = jComboCargo.getSelectedItem().toString();
        
        Cad_funcionarios cad_func = new Cad_funcionarios();
        cad_func.setCargo(cargo);
        cad_func.setCpf(cpf);
        cad_func.setMatricula(matricula);
        cad_func.setNome(nome);
        cad_func.setPermite_login(acessosis);
        cad_func.setSalario(salario);
        cad_func.setSenha(senha);
        
        cad_funcionariosDAO cad_DAO = new cad_funcionariosDAO();
        cad_DAO.insert(cad_func);
        
        jTextCPF.setText("");
        jTextMatricula.setText("");
        jTextNome.setText("");
        jTextSalario.setText("");
        jTextSenhaFunc.setText("");
        
    }//GEN-LAST:event_jButtonCadastrarActionPerformed

    private void jComboAcessosisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboAcessosisActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboAcessosisActionPerformed

    private void jTextIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextIDActionPerformed

    private void jButtonPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPesquisarActionPerformed
        // TODO add your handling code here:
        cad_funcionariosDAO funcionariosDAO = new cad_funcionariosDAO();
        List<Cad_funcionarios> listaFuncionarios = funcionariosDAO.getFuncByName(jTextNome.getText());
        
        DefaultTableModel modelo = (DefaultTableModel) tabelaFuncionarios.getModel();
        modelo.setRowCount(0);

        for (Cad_funcionarios c : listaFuncionarios ) {
            System.out.println("Nome: " + c.getNome());
            modelo.addRow(new Object[]{
                c.getId(),
                c.getMatricula(),
                c.getNome(),
                c.getCpf()
            });
        }
    }//GEN-LAST:event_jButtonPesquisarActionPerformed

    private void jButtonAtualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAtualizarActionPerformed
        // TODO add your handling code here:
        int id = Integer.parseInt(jTextID.getText());
        String cpf = jTextCPF.getText();
        int matricula = Integer.parseInt(jTextMatricula.getText());
        String nome = jTextNome.getText();
        double salario = Double.parseDouble(jTextSalario.getText());
        String senha = jTextSenhaFunc.getText();
        int acessosis = Integer.parseInt(jComboAcessosis.getSelectedItem().toString());
        String cargo = jComboCargo.getSelectedItem().toString();
        
        Cad_funcionarios cad_func = new Cad_funcionarios();
        cad_func.setId(id);
        cad_func.setCargo(cargo);
        cad_func.setCpf(cpf);
        cad_func.setMatricula(matricula);
        cad_func.setNome(nome);
        cad_func.setPermite_login(acessosis);
        cad_func.setSalario(salario);
        cad_func.setSenha(senha);
        
        cad_funcionariosDAO cad_DAO = new cad_funcionariosDAO();
        cad_DAO.update(cad_func);
        
        jTextID.setText("");
        jTextCPF.setText("");
        jTextMatricula.setText("");
        jTextNome.setText("");
        jTextSalario.setText("");
        jTextSenhaFunc.setText("");
    }//GEN-LAST:event_jButtonAtualizarActionPerformed

    private void jButtonExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonExcluirActionPerformed
        // TODO add your handling code here:
        String nome = jTextNome.getText();
        cad_funcionariosDAO funcionariosDAO = new cad_funcionariosDAO();
        funcionariosDAO.delete(nome);
        
        jTextID.setText("");
        jTextCPF.setText("");
        jTextMatricula.setText("");
        jTextNome.setText("");
        jTextSalario.setText("");
        jTextSenhaFunc.setText("");
    }//GEN-LAST:event_jButtonExcluirActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        cad_funcionariosDAO funcionariosDAO = new cad_funcionariosDAO();
        List<Cad_funcionarios> listaFuncionarios = funcionariosDAO.getFunc();
        
        DefaultTableModel model = (DefaultTableModel) tabelaFuncionarios.getModel();

        for (Cad_funcionarios c : listaFuncionarios ) {
            System.out.println("Nome: " + c.getNome());
            model.addRow(new Object[]{
                c.getId(),
                c.getMatricula(),
                c.getNome(),
                c.getCpf()
            });
        }
    }//GEN-LAST:event_formWindowOpened

    private void tabelaFuncionariosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelaFuncionariosMouseClicked
        JTable source = (JTable) evt.getSource();
        String id = source.getModel().getValueAt(source.getSelectedRow(), 0) + "";

        cad_funcionariosDAO funcionariosDAO = new cad_funcionariosDAO();
        Cad_funcionarios funcionario = funcionariosDAO.getFuncById(id);
        
        // System.out.println("ID: " + funcionario.getId() + ", NOME: " + funcionario.getNome());
        jTextID.setText(String.valueOf(funcionario.getId()));
        jTextCPF.setText(funcionario.getCpf());
        jTextMatricula.setText(String.valueOf(funcionario.getMatricula()));
        jTextNome.setText(funcionario.getNome());
        jTextSalario.setText(String.valueOf(funcionario.getSalario()));
        // jTextSenhaFunc.setText();
    }//GEN-LAST:event_tabelaFuncionariosMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAtualizar;
    private javax.swing.JButton jButtonCadastrar;
    private javax.swing.JButton jButtonExcluir;
    private javax.swing.JButton jButtonPesquisar;
    private javax.swing.JComboBox<String> jComboAcessosis;
    private javax.swing.JComboBox<String> jComboCargo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextCPF;
    private javax.swing.JTextField jTextID;
    private javax.swing.JTextField jTextMatricula;
    private javax.swing.JTextField jTextNome;
    private javax.swing.JTextField jTextSalario;
    private javax.swing.JTextField jTextSenhaFunc;
    private javax.swing.JTable tabelaFuncionarios;
    // End of variables declaration//GEN-END:variables
}
